name: Deploy to Railway

on:
  push:
    branches:
      - main  # Ou a branch que você deseja monitorar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ajuste a versão conforme necessário

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=$(openssl rand -base64 64)" >> $GITHUB_ENV
          echo "RAILWAY_PROJECT_ID=748fa302-08c4-4fda-be99-d31c9e7a32ac" >> $GITHUB_ENV
          echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - name: Run Django tests
        run: |
          poetry run python manage.py test --noinput

      - name: Deploy with Railway CLI
        run: |
          railway up --service bookstore
          

    # test